
server:
  port: 1000

spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/jd
    username: jdbean
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mybatis/*.xml